[build]
  publish   = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Статическая страница /docs
[[redirects]]
  from = "/docs"
  to   = "/docs/index.html"
  status = 200
