# Netlify configuration for bacon-docs

[build]
  # Папка, которая публикуется как сайт
  publish = "public"
  # Папка с серверными функциями (Netlify Functions)
  functions = "netlify/functions"

# Проксируем вызовы API на Netlify Function /api/view → /.netlify/functions/view
[[redirects]]
  from = "/api/view"
  to = "/.netlify/functions/view"
  status = 200

# Редирект с корня сайта на /docs (чтобы главная сразу открывала нужную страницу)
[[redirects]]
  from = "/"
  to = "/docs"
  status = 301
  force = true
